from django.urls import path
from . import views

urlpatterns = [
    path('', views.home, name='home'),
    path('login/', views.login_view, name='login'),
    path('signup/', views.signup, name='signup'),
    path('admin/home/', views.admin_home, name='admin_home'),
    path('admin/managers/', views.manager_list_adm, name='manager_list_adm'),
    path('admin/managers/add/', views.add_manager_adm, name='add_manager_adm'),
    path('admin/managers/<int:reg_id>/edit/', views.edit_manager_adm, name='edit_manager_adm'),
    path('admin/managers/<int:reg_id>/toggle/', views.toggle_manager_adm, name='toggle_manager_adm'),
    path('admin/managers/<int:reg_id>/delete/', views.delete_manager_adm, name='delete_manager_adm'),
    path('admin/drivers/', views.driver_list_adm, name='driver_list_adm'),
    path('admin/drivers/add/', views.add_driver_adm, name='add_driver_adm'),
    path('admin/drivers/<int:driver_id>/edit/', views.edit_driver_adm, name='edit_driver_adm'),
    path('admin/drivers/<int:driver_id>/toggle/', views.toggle_driver_adm, name='toggle_driver_adm'),
    path('admin/drivers/<int:driver_id>/delete/', views.delete_driver_adm, name='delete_driver_adm'),
    path('admin/trips/', views.trips_admin, name='trips_admin'),
    path('admin/trips/report/', views.trips_report_admin, name='trips_report_admin'),
    path('manager/home/', views.manager_home, name='manager_home'),
    path('manager/vehicles/', views.vehicles_page, name='vehicles_page'),
    path('manager/drivers/', views.drivers_page, name='drivers_page'),
    path('manager/trips/', views.trips_page, name='trips_page'),
    path('manager/reports/completed-trips/', views.manager_completed_trips, name='manager_completed_trips'),
    path('manager/vehicles/create/', views.vehicle_create, name='vehicle_create'),
    path('manager/vehicles/<int:vehicle_id>/', views.vehicle_detail, name='vehicle_detail'),
    path('manager/vehicles/<int:vehicle_id>/edit/', views.vehicle_edit, name='vehicle_edit'),
    path('manager/vehicles/<int:vehicle_id>/delete/', views.vehicle_delete, name='vehicle_delete'),
    path('manager/drivers/<int:driver_id>/', views.driver_detail, name='driver_detail'),
    path('manager/drivers/<int:driver_id>/assign-vehicle/', views.assign_vehicle, name='assign_vehicle'),
    path('manager/drivers/<int:driver_id>/unassign-vehicle/', views.unassign_vehicle, name='unassign_vehicle'),
    path('manager/trips/create/', views.create_trip, name='create_trip'),
    path('driver/home/', views.driver_home, name='driver_home'),
    path('driver/trips/', views.driver_trips, name='driver_trips'),
    path('driver/trips/<int:trip_id>/', views.trip_detail, name='trip_detail'),
    path('driver/trips/<int:trip_id>/complete/', views.trip_complete_form, name='trip_complete_form'),
    path('driver/reports/completed-trips/', views.driver_completed_trips, name='driver_completed_trips'),
    path('driver/vehicle/', views.driver_vehicle_detail, name='driver_vehicle_detail'),
    path('logout/', views.logout_view, name='logout'),
]
