# Generated by Django 6.0.1 on 2026-02-23 18:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('s_fleet', '0002_vehicle_driver_mlfeaturerecord_trip_predictionresult_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='driver',
            name='address',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='driver',
            name='emergency_contact_name',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
        migrations.AddField(
            model_name='driver',
            name='emergency_contact_phone',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='driver',
            name='license_expiry_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='driver',
            name='phone_number',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='driver',
            name='years_of_experience',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
