# Generated by Django 4.1.7 on 2026-03-03 06:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('s_fleet', '0003_driver_address_driver_emergency_contact_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vehicle',
            name='make_and_model',
        ),
    ]
