# Generated by Django 4.1.7 on 2026-03-09 06:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('s_fleet', '0005_trip_actual_distance_km_trip_end_address_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mlfeaturerecord',
            name='fuel_consumption',
        ),
        migrations.RemoveField(
            model_name='trip',
            name='expected_fuel_liters',
        ),
        migrations.RemoveField(
            model_name='trip',
            name='fuel_used_liters',
        ),
        migrations.RemoveField(
            model_name='tripcompletion',
            name='fuel_cost',
        ),
        migrations.RemoveField(
            model_name='tripcompletion',
            name='fuel_filled',
        ),
        migrations.AlterField(
            model_name='alert',
            name='alert_type',
            field=models.CharField(choices=[('maintenance', 'Maintenance'), ('driver_risk', 'Driver Risk')], max_length=20),
        ),
        migrations.DeleteModel(
            name='FuelLog',
        ),
    ]
