# Generated by Django 4.1.7 on 2026-03-09 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('s_fleet', '0006_remove_mlfeaturerecord_fuel_consumption_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alert',
            name='alert_type',
            field=models.CharField(choices=[('maintenance', 'Maintenance'), ('trip', 'Trip'), ('driver_risk', 'Driver Risk')], max_length=20),
        ),
    ]
