# Generated by Django 4.1.7 on 2026-03-11 06:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('s_fleet', '0008_trippayment_tripitem_tripexpense'),
    ]

    operations = [
        migrations.AddField(
            model_name='trip',
            name='planned_destination',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
        migrations.AddField(
            model_name='trip',
            name='planned_origin',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
    ]
