# Generated by Django 4.1.7 on 2026-03-12 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('s_fleet', '0009_trip_planned_destination_trip_planned_origin'),
    ]

    operations = [
        migrations.AddField(
            model_name='driver',
            name='bank_account_last4',
            field=models.CharField(blank=True, max_length=4, null=True),
        ),
        migrations.AddField(
            model_name='driver',
            name='bank_name',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
        migrations.AddField(
            model_name='driver',
            name='payment_method',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='driver',
            name='upi_id',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
    ]
