# Generated by Django 4.1.7 on 2026-03-12 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('s_fleet', '0010_driver_bank_account_last4_driver_bank_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='driver',
            name='bank_account_last4',
        ),
        migrations.RemoveField(
            model_name='driver',
            name='bank_name',
        ),
        migrations.RemoveField(
            model_name='driver',
            name='payment_method',
        ),
        migrations.RemoveField(
            model_name='driver',
            name='upi_id',
        ),
        migrations.AddField(
            model_name='trippayment',
            name='gateway_order_id',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
        migrations.AddField(
            model_name='trippayment',
            name='gateway_payment_id',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
        migrations.AddField(
            model_name='trippayment',
            name='gateway_signature',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='trippayment',
            name='payment_gateway',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
