# Generated by Django 4.1.7 on 2026-03-12 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('s_fleet', '0011_remove_driver_bank_account_last4_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='trip',
            name='planned_destination_lat',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='trip',
            name='planned_destination_lng',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='trip',
            name='planned_destination_place_id',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
        migrations.AddField(
            model_name='trip',
            name='planned_origin_lat',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='trip',
            name='planned_origin_lng',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='trip',
            name='planned_origin_place_id',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
    ]
