# Generated by Django 6.0.1 on 2026-03-23 08:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('s_fleet', '0013_triplocation'),
    ]

    operations = [
        migrations.AddField(
            model_name='tripexpense',
            name='receipt',
            field=models.FileField(blank=True, null=True, upload_to='receipts/'),
        ),
    ]
